#!/bin/bash

echo "sed -n 's/g/fox/p' ../input/sample.txt > ../output/g-to-fox-sample-1.txt && echo ran sed 1 time"
echo "sed -n 's/g/fox/p' ../input/sample.txt > ../output/g-to-fox-sample-2.txt && echo ran sed 2 times"
echo "sed -n 's/g/fox/p' ../input/sample.txt > ../output/g-to-fox-sample-3.txt && echo ran sed 3 times"
echo "sed -n 's/g/fox/p' ../input/sample.txt > ../output/g-to-fox-sample-4.txt && echo ran sed 4 times"
echo "sed -n 's/g/fox/p' ../input/sample.txt > ../output/g-to-fox-sample-5.txt && echo ran sed 5 times"
echo "sed -n 's/g/fox/p' ../input/sample.txt > ../output/g-to-fox-sample-6.txt && echo ran sed 6 times"
echo "sed -n 's/g/fox/p' ../input/sample.txt > ../output/g-to-fox-sample-7.txt && echo ran sed 7 times"
# echo "sed -n 's/g/fox/p' ../input/sample.txt"
# echo "sed -n 's/g/fox/p' ../input/sample.txt"
# echo "sed -n 's/g/fox/p' ../input/sample.txt"
# echo "sed -n 's/g/fox/p' ../input/sample.txt"
# echo "sed -n 's/g/fox/p' ../input/sample.txt"
# echo "sed -n 's/g/fox/p' ../input/sample.txt"
# echo "sed -n 's/g/fox/p' ../input/sample.txt"